### ISSUE TITLE
Where do these codes come from?

### ISSUE THREAD

**Issue by deostroll** [Arn-O/py-android-accessory#9]
First of all, love your article...I'm very excited to see this running on my pc.

I don't understand from where you get these [codes](https://github.com/Arn-O/py-android-accessory/blob/master/client/pyaccessory.py#L8-L9):

```
VID_GALAXY_NEXUS_DEBUG = 0x04e8
PID_GALAXY_NEXUS_DEBUG = 0x6860
```

Is it something we manually set so that our android app can be turned on to accessory mode, or are these some standard values in which case I don't find them on developer.android.com

**Comment by Arn-O** [comment]
Hi deostroll.

First of all, thank you for your nice comment. Really appreciated.

I had to used these codes to have my device recognized after activating the developer settings:

http://developer.android.com/tools/device.html

This activation changes the USB interface. This is not required to activate the accessory mode, but it is required to develop in Android Studio and test on the physical HW. I do not know if it is standard to all Android devices or not. Probably not, since the VID is the one from Samsung, and not the one from Google.

Let me know if you have further questions.

Ar.

**Comment by deostroll** [comment]
I was able to find it successfully myself. First had to google and found the VID corresponding to my device (listed in one of the search results itself). Then when I did a `lsusb` and studied the output I recognized that VID, and took the PID listed against it.

**Comment by Arn-O** [comment]
Excellent!

For reference, the list here is also useful: http://www.linux-usb.org/usb.ids

For reference also, the issue #1 is related to the mobile device identification. So far, I do not know how to make it clean.

Ar.
